# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'subreg2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sr


class Ui_MainWindow(object):
    fileslist=[]
    name=""
    format=""
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 547)
        MainWindow.setFixedSize(MainWindow.size())
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(20, 60, 361, 411))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.renameButton = QtWidgets.QPushButton(self.frame)
        self.renameButton.setGeometry(QtCore.QRect(230, 350, 111, 41))
        self.renameButton.setObjectName("renameButton")
        self.renameButton.clicked.connect(self.renclicked)
        self.pathtext = QtWidgets.QLabel(self.frame)
        self.pathtext.setGeometry(QtCore.QRect(10, 20, 71, 21))
        self.pathtext.setObjectName("pathtext")
        self.nametext = QtWidgets.QLabel(self.frame)
        self.nametext.setGeometry(QtCore.QRect(10, 60, 91, 20))
        self.nametext.setObjectName("nametext")
        self.formattext = QtWidgets.QLabel(self.frame)
        self.formattext.setGeometry(QtCore.QRect(10, 100, 61, 20))
        self.formattext.setObjectName("formattext")
        self.numbertext = QtWidgets.QLabel(self.frame)
        self.numbertext.setGeometry(QtCore.QRect(10, 140, 121, 19))
        self.numbertext.setObjectName("numbertext")
        self.previewtext = QtWidgets.QLabel(self.frame)
        self.previewtext.setGeometry(QtCore.QRect(10, 180, 67, 19))
        self.previewtext.setObjectName("previewtext")
        self.pathbox = QtWidgets.QLineEdit(self.frame)
        self.pathbox.setGeometry(QtCore.QRect(100, 20, 241, 27))
        self.pathbox.setObjectName("pathbox")
        self.namebox = QtWidgets.QLineEdit(self.frame)
        self.namebox.setGeometry(QtCore.QRect(100, 60, 113, 27))
        self.namebox.setObjectName("namebox")
        self.formatbox = QtWidgets.QLineEdit(self.frame)
        self.formatbox.setGeometry(QtCore.QRect(100, 100, 51, 27))
        self.formatbox.setObjectName("formatbox")
        self.numberbox = QtWidgets.QLineEdit(self.frame)
        self.numberbox.setGeometry(QtCore.QRect(130, 140, 31, 27))
        self.numberbox.setObjectName("numberbox")
        self.textBrowser = QtWidgets.QTextBrowser(self.frame)
        self.textBrowser.setGeometry(QtCore.QRect(70, 180, 271, 151))
        self.textBrowser.setObjectName("textBrowser")
        self.pereviewbutton = QtWidgets.QPushButton(self.frame)
        self.pereviewbutton.setGeometry(QtCore.QRect(110, 350, 111, 41))
        self.pereviewbutton.setObjectName("pereviewbutton")
        self.pereviewbutton.clicked.connect(self.perclicked)
        self.subreg_title = QtWidgets.QLabel(self.centralwidget)
        self.subreg_title.setGeometry(QtCore.QRect(130, 20, 131, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(36, 31, 49))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(36, 31, 49, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(36, 31, 49))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(36, 31, 49, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 190, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.subreg_title.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.subreg_title.setFont(font)
        self.subreg_title.setTextFormat(QtCore.Qt.AutoText)
        self.subreg_title.setScaledContents(False)
        self.subreg_title.setAlignment(QtCore.Qt.AlignCenter)
        self.subreg_title.setObjectName("subreg_title")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SUBREG"))
        self.renameButton.setText(_translate("MainWindow", "rename"))
        self.pathtext.setText(_translate("MainWindow", "Directory :"))
        self.nametext.setText(_translate("MainWindow", "Series Name:"))
        self.formattext.setText(_translate("MainWindow", "Format:"))
        self.numbertext.setText(_translate("MainWindow", "Season Number :"))
        self.previewtext.setText(_translate("MainWindow", "Preview:"))
        self.pereviewbutton.setText(_translate("MainWindow", "preview"))
        self.subreg_title.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#e01b24;\">SUBREG</span></p></body></html>"))
    def perclicked(self):
        if(self.pathbox.text()!="" and self.namebox.text()!="" and self.formatbox.text()!="" and self.numberbox.text()!=""):
            try:
                self.fileslist = sr.filefinderandsorter(self.pathbox.text(),self.formatbox.text())
                self.name = self.namebox.text()+"S"+self.numberbox.text()+"E"
                self.format="."+self.formatbox.text()
                self.textBrowser.setText(sr.preview(self.fileslist,self.format,self.name))
            except:
                msg = QtWidgets.QMessageBox()
                msg.setWindowTitle("error")
                msg.setIcon(QtWidgets.QMessageBox.Icon.Critical)
                msg.setText("Somthing Worng!\nPlease try again")
                x = msg.exec_()
        else:
            msg = QtWidgets.QMessageBox()
            msg.setWindowTitle("error")
            msg.setIcon(QtWidgets.QMessageBox.Icon.Critical)
            msg.setText("Please fill all the items")
            x = msg.exec_()
    def renclicked(self):
        if(self.pathbox.text()!="" and self.namebox.text()!="" and self.formatbox.text()!="" and self.numberbox.text()!=""):
            try:
                sr.reg(self.fileslist,self.pathbox.text(),self.name,self.format)
            except:
                msg = QtWidgets.QMessageBox()
                msg.setWindowTitle("error")
                msg.setIcon(QtWidgets.QMessageBox.Icon.Critical)
                msg.setText("Somthing Worng!\nPlease try again")
                x = msg.exec_()
        else:
            msg = QtWidgets.QMessageBox()
            msg.setWindowTitle("error")
            msg.setIcon(QtWidgets.QMessageBox.Icon.Critical)
            msg.setText("Please fill all the items")
            x = msg.exec_()

            

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
